'use client'

import { Bug, Building2, Home, Leaf, MousePointer2, ShieldCheck, Sparkles, Star, Stethoscope, ClipboardCheck, PhoneCall } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { InspectionModal } from '@/components/modals/inspection-modal'

const services = [{ icon: Home, title: 'Residential', copy: 'A smarter, safer plan for the place you call home.' }, { icon: Building2, title: 'Commercial', copy: 'Reliable protection that keeps your business moving.' }, { icon: Bug, title: 'Termite Control', copy: 'Stop hidden damage before it starts.' }, { icon: MousePointer2, title: 'Rodent Control', copy: 'Humane, thorough removal and prevention.' }, { icon: Leaf, title: 'Mosquito Control', copy: 'Enjoy your yard again with family-conscious treatments.' }, { icon: Stethoscope, title: 'Bed Bugs', copy: 'Discreet, effective treatments with a clear plan.' }]
const reviews = [{ name: 'Sarah M.', quote: 'Clint took the time to explain everything and never made us feel rushed. The difference is night and day.', place: 'Homeowner in North Texas' }, { name: 'Jason R.', quote: 'No splash and dash here. They found the source, fixed it, and followed up exactly when they said they would.', place: 'Homeowner in Plano' }, { name: 'Megan T.', quote: 'Professional, kind, and careful around our dog. We finally feel comfortable using our backyard again.', place: 'Homeowner in Frisco' }, { name: 'David L.', quote: 'It is rare to get this level of personal service. Wise Choice earned a customer for life.', place: 'Business owner in McKinney' }]

export function Hero() { return <section id="top" className="overflow-hidden bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:py-28"><div><Badge variant="outline" className="border-primary-foreground/30 bg-primary-foreground/10 text-primary-foreground">LOCAL · LICENSED · OWNER-OPERATED</Badge><h1 className="mt-6 max-w-3xl font-serif text-5xl font-bold leading-[1.02] tracking-tight text-balance sm:text-6xl lg:text-7xl">Thorough pest control you can count on.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-primary-foreground/75">We love helping our community stay pest-free. With Wise Choice, you get honest advice, careful work, and Clint or Brian on the job.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="tel:+19727439284"><Button size="lg" variant="secondary" className="w-full sm:w-auto"><PhoneCall data-icon="inline-start" />Call (972) 743-9284</Button></a><InspectionModal trigger={<Button size="lg" variant="outline" className="w-full border-primary-foreground/40 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 sm:w-auto">Request free inspection</Button>} /></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-primary-foreground/75"><span><ShieldCheck className="mr-2 inline size-4 text-accent" />Brother-owned</span><span><ShieldCheck className="mr-2 inline size-4 text-accent" />Satisfaction guarantee</span><span><ShieldCheck className="mr-2 inline size-4 text-accent" />Licensed & insured</span></div></div><div className="relative"><div className="rounded-[2rem] border border-primary-foreground/15 bg-primary-foreground/10 p-3"><img src="/images/clint-brian.png" alt="Clint and Brian outside a North Texas home" className="aspect-[4/3] w-full rounded-[1.5rem] object-cover" /></div><div className="absolute -bottom-5 -left-4 rounded-xl bg-accent px-5 py-4 text-accent-foreground shadow-xl"><p className="font-serif text-2xl font-bold">Your neighbors.</p><p className="text-sm font-semibold">Your pest experts.</p></div></div></div></section> }

export function Owners() { return <section id="story" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-accent">The Wise Choice difference</p><h2 className="mt-4 font-serif text-4xl font-bold tracking-tight text-primary sm:text-5xl">Big enough to solve it.<br />Small enough to care.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">We&apos;re Clint and Brian — brothers, North Texans, and the owners of Wise Choice Pest Control. We started this company because your home deserves more than a quick spray and a goodbye.</p><p className="mt-4 leading-7 text-muted-foreground">When you call us, you get the owners. We listen carefully, explain clearly, and build a plan that makes sense for your home, your family, and your budget.</p><InspectionModal trigger={<Button className="mt-8">Meet us with a free inspection</Button>} /></div><div className="rounded-[2rem] bg-secondary p-8"><p className="font-serif text-3xl font-bold leading-tight text-primary">“We don&apos;t just treat symptoms. We take the time to understand the whole picture.”</p><p className="mt-6 text-sm font-bold uppercase tracking-wider text-accent">— Clint & Brian</p></div></section> }

export function Services() { return <section id="services" className="bg-secondary"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-accent">How we help</p><h2 className="mt-4 font-serif text-4xl font-bold text-primary sm:text-5xl">Protection for every corner of life.</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(({ icon: Icon, title, copy }) => <Card key={title} className="group border-border/70 bg-background transition hover:-translate-y-1 hover:shadow-lg"><CardContent className="flex min-h-52 flex-col p-6"><Icon className="size-8 text-accent" /><h3 className="mt-8 font-serif text-2xl font-bold text-primary">{title}</h3><p className="mt-2 leading-6 text-muted-foreground">{copy}</p><InspectionModal trigger={<button className="mt-auto pt-5 text-left text-sm font-bold text-primary underline decoration-accent decoration-2 underline-offset-4">Book service →</button>} /></CardContent></Card>)}</div></div></section> }

export function WhyUs() { const items = [{ icon: Sparkles, title: 'No splash & dash', copy: 'Thoughtful work, not a rushed routine.' }, { icon: ShieldCheck, title: 'Owner-operated', copy: 'Clint or Brian is always close by.' }, { icon: Leaf, title: 'Family conscious', copy: 'Careful choices for pets and people.' }, { icon: Star, title: 'Guaranteed results', copy: 'Peace of mind backed by our promise.' }]; return <section id="why-us" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-accent">Why neighbors choose us</p><h2 className="mt-4 font-serif text-4xl font-bold text-primary sm:text-5xl">The right choice feels different.</h2></div><p className="max-w-xl text-lg leading-8 text-muted-foreground">You deserve a pest control partner who treats your property like it belongs to someone they know — because it does.</p></div><div className="mt-12 grid gap-8 border-y border-border py-10 sm:grid-cols-2 lg:grid-cols-4">{items.map(({ icon: Icon, title, copy }) => <div key={title}><Icon className="size-7 text-accent" /><h3 className="mt-5 font-bold text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}</div></section> }

export function Process() { return <section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-accent">Simple from day one</p><h2 className="mt-4 font-serif text-4xl font-bold sm:text-5xl">A better plan starts with a conversation.</h2></div><div className="mt-14 grid gap-10 md:grid-cols-3">{[['01','Inspect','We listen, look closely, and find the real source of the problem.'],['02','Create a custom plan','You get clear recommendations — no mystery, no pressure.'],['03','Enjoy peace of mind','We do the work thoroughly and stand behind the result.']].map(([num,title,copy]) => <div key={num} className="border-t border-primary-foreground/20 pt-6"><span className="font-mono text-sm text-accent">{num}</span><h3 className="mt-8 font-serif text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-primary-foreground/70">{copy}</p></div>)}</div></div></section> }

export function Reviews() { return <section id="reviews" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-accent">Kind words from neighbors</p><h2 className="mt-4 font-serif text-4xl font-bold text-primary sm:text-5xl">The proof is in the peace of mind.</h2></div><div className="flex items-center gap-2 text-primary"><span className="text-2xl tracking-widest text-accent">★★★★★</span><span className="text-sm font-bold">5.0 on Google</span></div></div><div className="mt-12 grid gap-4 md:grid-cols-2">{reviews.map((review) => <Card key={review.name} className="border-border/70"><CardContent className="p-7"><div className="text-accent">★★★★★</div><p className="mt-5 font-serif text-xl font-semibold leading-8 text-primary">“{review.quote}”</p><p className="mt-6 text-sm font-bold text-primary">{review.name}</p><p className="mt-1 text-xs text-muted-foreground">{review.place}</p></CardContent></Card>)}</div></section> }

export function Contact() { return <section id="contact" className="bg-secondary"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-accent">Let&apos;s get started</p><h2 className="mt-4 font-serif text-4xl font-bold text-primary sm:text-5xl">Ready to make pests someone else&apos;s problem?</h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Tell us what&apos;s going on and we&apos;ll help you figure out the next best step. No pressure. Just good advice from people who care.</p><InspectionModal trigger={<Button size="lg" className="mt-8">Request a free inspection</Button>} /></div><Card className="border-0 bg-primary text-primary-foreground"><CardContent className="flex flex-col gap-8 p-8"><div><PhoneCall className="size-7 text-accent" /><p className="mt-4 text-sm text-primary-foreground/60">Call or text</p><a href="tel:+19727439284" className="font-serif text-3xl font-bold">(972) 743-9284</a></div><div><ClipboardCheck className="size-7 text-accent" /><p className="mt-4 text-sm text-primary-foreground/60">Service hours</p><p className="mt-1 font-bold">Monday–Saturday · 8am–6pm</p></div><div><Home className="size-7 text-accent" /><p className="mt-4 text-sm text-primary-foreground/60">Proudly serving</p><p className="mt-1 font-bold">North Texas and surrounding communities</p></div></CardContent></Card></div></section> }
